# Generated by Django 3.1.4 on 2020-12-20 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='leader_mobile',
            field=models.CharField(default='', max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Enter a valid mobile number', regex='^(\\+\\d{1,3}[- ]?)?\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='discord_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
