# Generated by Django 3.1.4 on 2020-12-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_team_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader_email',
        ),
    ]
